<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/config/config.index.js');
?>
<!--<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />-->
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />

<div class="viewMain">
  <div class ="genericWrapperTopRight">
    <?php
    echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
    echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
    echo $this->t('Back');  
    echo "</a>";
    echo '</div>';
   ?>
  </div>
  <div>
    <form class="pyslicerConfigForm" method="POST" action="<?php echo $this->webroot?>/pyslicer/config">
      <label>Slicer Proxy Server URL</label>
      <input id="slicerProxyUrl" type="text" value="<?php echo $this->slicerProxyUrl?>" name="slicerProxyUrl" />
      <input class="globalButton" type="submit" name="submitConfig" value="Save" />
    </form>
  </div>
</div>






