<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<h2>Available Slicer Pipelines</h2>
<?php
  $pipelines = array('volumerendering' => 'Volume Rendering',
                     'segmentation' => 'Segmentation',
                     'registration' => 'Registration');
  foreach($pipelines as $pipeline => $label)
    {
    echo '<a href="'.$this->webroot . '/pyslicer/pipeline/'.$pipeline.'">'.$label.'</a>';  
    }
?>

