<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/console/console.pyslicer.js');
?>
<h2>Welcome to the Pyslicer Module</h2>

<textarea id='pyslicer_console' rows="20" cols="50">
</textarea>
