<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/index/pyslicer.index.js');
?>
<?php
           
    
  echo '<ul id="midas_pyslicer_pipelines">';
  echo '<li><a href="javascript:;" class="volumeRendering" ><img alt="" src=""/>Volume Rendering</a></li>';
  echo '<li><a href="javascript:;" class="segmentation" ><img alt="" src=""/>Segmentation</a></li>';
  echo '<li><a href="javascript:;" class="registration" ><img alt="" src=""/>Registration</a></li>';
  echo "</ul>";
    
?>

