<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/


 
//$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.tablesorter.min.js');
$this->headScript()->appendFile($this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/process/process.status.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/layout/pyslicer.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/process/process.status.css" />

<div id="jobstatus" class="viewMain" >
<?php
echo '<ul id="midas_pyslicer_jobstatus_header">';
echo "<li><span class='key'>Name:</span> " .$this->job->getName().'</li>';
echo '<li><span class="key">Status:</span> <span id="midas_pyslicer_job_status" class="'.$this->statusClasses[$this->job->getStatus()].'">'.$this->statusStrings[$this->job->getStatus()].'</span></li>';
echo "<li><span class='key'>Params:</span> " .$this->job->getParams().'</li>';
echo "<li><span class='key'>Script:</span> " .$this->job->getScript().'</li>';
echo "<li><span class='key'>Creation Date:</span> " .$this->job->getCreationDate().'</li>';
echo "</ul>";

if(sizeof($this->jobConditionLines) > 0)
  {
  echo '<div id="midas_pyslicer_error_div"><span class="midas_pyslicer_error">Error Trace:</span>';
  echo '<ul id="midas_pyslicer_jobstatus_condition">';
  foreach($this->jobConditionLines as $errorLine)
    {
    echo '<li>'.$errorLine.'</li>';
    }
  echo "</ul></div>";
  }

echo '<div class="tableTitle">Pipeline Progress</div>';
echo '<div class="tableContainer">';
echo '<img style="display: none;" id="midas_pyslicer_jobstatuses_loading" alt="Loading..." src="'.$this->coreWebroot.'/public/images/icons/loading.gif" />';
echo '<table style="display: none;" id="midas_pyslicer_jobstatuses"><thead>';
$headers = array('Event', 'Message', 'Completion Time');
echo '<tr>';
foreach($headers as $header)
  {
  echo '<th>' . $header . '</th>';
  }
echo '</tr></thead><tbody>';

foreach($this->jobStatuses as $jobstatus)
  {
  echo '<tr class="statusRow">';
  echo '<td>' . $jobstatus->getEventType() . '</td>';
  echo '<td>' . $jobstatus->getMessage() . '</td>';
  echo '<td>' . $jobstatus->getNotifyDate() . '</td>';
  echo '</tr>';  
  }
echo '</tbody></table></div>';

echo '<div class="viewInput"><span class="key">Input:</span> ';
foreach($this->insAndOuts['inputs'] as $input)
  {
  echo '<a href="'.$input['url'].'">'.$input['text'].'</a>';  
  }
echo '</div>';
echo '<div class="viewOutput"><span class="key">Output:</span> ';
foreach($this->insAndOuts['outputs'] as $output)
  {
  echo '<a class="outputLink" href="'.$output['url'].'">';
  echo $output['text'].'</a>';  
  }
echo '</div>';
?>


</div>



