<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/


 
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.tablesorter.min.js');
$this->headScript()->appendFile($this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/process/process.statuslist.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/layout/pyslicer.css" />

<div id="showjobs" class="viewMain">
  
    
  <h3>Start a new pipeline job</h3>  
  <div id="slicerPipelines">
    <ul>
      <li><a href="javascript:;" id="segmentation" class="slicerPipeline" ><img alt="" src=""/>Simple Region Growing Segmentation</a></li>
      <li><a href="javascript:;" id="registration" class="slicerPipeline" ><img alt="" src=""/>Registration</a></li>
      <li><a href="javascript:;" id="pdfsegmentation" class="slicerPipeline" ><img alt="" src=""/>Interactive PDF Segmentation (TubeTK)</a>
          <ul><a href="<?php echo $this->webroot?>/user/settings">Before first run: set default folders for PDF segmenter</a></ul>
      </li>
    </ul>  
  </div>
  
    
  <h3>Previous job statuses</h3>
  <table class="tablesorter" id="tablesorter_pyslicer_jobs_status">
    <thead>
      <tr class="header">
      <?php
        foreach($this->columnHeaders as $column => $header)
          {
          echo "<th class='statuscol'>".$header."</th>";
          }
      ?>
      </tr>
      </thead>
      <tbody>
        <?php       
          $stripeClasses = array('odd', 'even');
          $stripeClassInd = 0;
          foreach($this->jobsRows as $jobRow)
            {
            echo "<tr class='resultsRow ".$stripeClasses[$stripeClassInd++ % 2]."'>";
            foreach($this->columnHeaders  as $column => $header)
              {
              if($column === 'name')
                {
                $nameString = '<a href="'.$jobRow['name_url'].'">'.$jobRow['name_string'].'</a>';
                echo "<td>".$nameString."</td>";
                }
              elseif($column === 'status')
                {
                $statusString = $jobRow['status_string'];
                $statusClass = $jobRow['status_class'];
                echo '<td class="'.$statusClass.'" >'.$statusString."</td>";
                }
              elseif($column === 'output')
                {
                $outputString = $jobRow['output_string'];
                $outputUrl = $jobRow['output_url'];
                $outputQtip = $jobRow['output_qtip'];
                // TODO something with qtip
                $outputString = '<a href="'.$outputUrl.'">'.$outputString.'</a>';
                echo "<td>".$outputString."</td>";
                }
              elseif($column === 'params')
                {
                echo '<td><a qtip=\''.$jobRow[$column].'\' class="paramsLink">Show</a></td>';
                }
              else
                {
                $colVal = $jobRow[$column];
                echo "<td>".$colVal."</td>";
                }
              }
            echo "</tr>";
            }
        ?> 
    </tbody>
  </table>
</div>



